# .air.toml
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]

  cmd = "templ generate; go build -o ./tmp/main.exe ./cmd/server/main.go"
  
  # Addressing the deprecation warning
  entrypoint = ["tmp\\main.exe"]
  
  # Standard Air settings
  root = "."
  testdata_dir = "testdata"
  tmp_dir = "tmp"
  include_ext = ["go", "tpl", "tmpl", "html", "templ"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "legacy", "static"]
  include_dir = ["cmd", "internal", "views"]
  exclude_regex = ["_test.go", "_templ.go"]
  delay = 1000
  stop_on_error = true
  log = "build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true